apiVersion: v1
kind: Service
metadata:
  name: __SERVICE_NAME__
  namespace: __NAMESPACE__
  labels:
    app: __APP_NAME__
    app.kubernetes.io/name: __APP_NAME__
    app.kubernetes.io/component: ui
    app.kubernetes.io/environment: __ENVIRONMENT__
  annotations:
    cloud.google.com/backend-config: '{"default": "dhg-rateauto-dev-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: __SERVICE_PORT__
      targetPort: __CONTAINER_PORT__
      protocol: TCP
  selector:
    app: __APP_NAME__