apiVersion: v1
kind: ServiceAccount
metadata:
  name: __SERVICE_ACCOUNT_NAME__
  namespace: __NAMESPACE__
  labels:
    app: __APP_NAME__
    app.kubernetes.io/name: __APP_NAME__
    app.kubernetes.io/environment: __ENVIRONMENT__
